const AUTH_ERROR_CODES = Object.freeze({
    ACCESS_TOKEN_MISSING: "ACCESS_TOKEN_MISSING",
    ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
    ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
    ACCESS_TOKEN_NOT_ACTIVE: "ACCESS_TOKEN_NOT_ACTIVE",
})

AUTH_INTERCEPTOR_CONFIG = {
    RETRY_FLAG: "_authRetry",
    ROTATE_ENDPOINT: "/auth/tokens/rotate",
}

export {
    AUTH_ERROR_CODES,
    AUTH_INTERCEPTOR_CONFIG
}